/**
 * Custom Cloudflare Worker entrypoint.
 *
 * WHY THIS FILE EXISTS
 * `wrangler.jsonc` declares a Cron Trigger (`triggers.crons`), but the worker generated by
 * @opennextjs/cloudflare exports ONLY a `fetch` handler. A Worker without a `scheduled`
 * export silently ignores its cron trigger, so the scan never ran on Cloudflare: the
 * deploy looked healthy and the dashboard simply stayed empty except for on-demand fetches.
 *
 * This entrypoint re-uses the generated fetch handler and adds the missing `scheduled`
 * handler, which drives the same code path as `GET /api/cron/scan`.
 *
 * See https://opennext.js.org/cloudflare/howtos/custom-worker
 */
// @ts-expect-error - generated at build time by `opennextjs-cloudflare build`.
import { default as handler } from './.open-next/worker.js';

export default {
  fetch: handler.fetch,

  /**
   * Cron Trigger handler.
   *
   * The scan runs through the app's own HTTP route rather than importing ScannerService
   * directly: the route already carries the batching, hydration and error handling, and
   * going through `fetch` guarantees the Next.js request context (and therefore the D1
   * binding lookup in src/lib/db.ts) is initialised exactly as it is for a normal request.
   *
   * `ctx.waitUntil` keeps the invocation alive until the scan settles, so Cloudflare
   * records the real outcome in the Cron Trigger "Past Events" table.
   */
  async scheduled(
    _controller: ScheduledController,
    env: Record<string, unknown>,
    ctx: ExecutionContext,
  ) {
    const secret = typeof env.CRON_SECRET === 'string' ? env.CRON_SECRET : undefined;
    const request = new Request('https://cron.invalid/api/cron/scan', {
      headers: secret ? { authorization: `Bearer ${secret}` } : {},
    });

    ctx.waitUntil(
      (async () => {
        try {
          const res = await handler.fetch(request, env, ctx);
          console.log(`[cron] scan finished: HTTP ${res.status} ${await res.text()}`);
        } catch (e) {
          // Never throw: an unhandled rejection marks the cron run as failed and buys
          // nothing, since the next trigger retries in five minutes anyway.
          console.error('[cron] scan failed:', e instanceof Error ? e.message : e);
        }
      })(),
    );
  },
};
